### ISSUE TITLE
漂流瓶

### ISSUE THREAD

**Issue by zhanghuidinah** [yejiayu/qs#1]
https://github.com/TJGResearch/docs/commit/7547f7de8c3e24a0c7dfbc6a97bfd89d6c2993a7

**Comment by yejiayu** [comment]
你也去 TJG 了?
在 2018年7月24日 +0800 PM4:04，Hui Zhang <notifications@github.com>，写道：

**Comment by zhanghuidinah** [comment]
没。。clever其他的people

**Comment by yejiayu** [comment]
all?
在 2018年7月24日 +0800 PM4:36，Hui Zhang <notifications@github.com>，写道：

**Comment by zhanghuidinah** [comment]
one of
